package com.connor.handicaptracker.dao.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "handicaps")
public class Handicap {
    public Handicap() {

    }

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    private String username;
    private double handicapIndex;

    public Handicap(String username, double handicapIndex) {
        this.username = username;
        this.handicapIndex = handicapIndex;
    }
    @DynamoDBHashKey(attributeName = "username")
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @DynamoDBRangeKey(attributeName = "handicap_index")
    public double getHandicapIndex() {
        return handicapIndex;
    }

    public void setHandicapIndex(double handicapIndex) {
        this.handicapIndex = handicapIndex;
    }

    @Override
    public String toString() {
        return "Handicap{}";
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }
}
