package com.connor.handicaptracker.dao.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "rounds")
public class Rounds implements Comparable<Rounds>{
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    // dates will be xx/xx/xx format
    private String date;
    private Course course;
    private double score;

    public Rounds() {

    }

    public Rounds(String date, Course course, double score) {
        this.date = date;
        this.course = course;
        this.score = score;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    // should be double instead of int
    @Override
    public int compareTo(Rounds otherRound) {
        // Compare rounds based on their scores
        return Double.compare(this.score, otherRound.score);
    }


}
