Resources:
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "players"

  HandicapsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "handicap_index"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "handicap_index"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "handicaps"

  CoursesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "course"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "course"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "courses"

  RoundsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "date"
          AttributeType: "S"
        - AttributeName: "score"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "date"
          KeyType: "HASH"
        - AttributeName: "score"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "rounds"